#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 26 11:54:06 EDT 2024
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim ALU_behav -key {Behavioral:sim_1:Functional:ALU} -tclbatch ALU.tcl -protoinst "protoinst_files/Lab_2.protoinst" -view /home/josh/projects/ece1195/lab_2/ALU_Logical_tb_behav.wcfg -log simulate.log
