webtalk_init -webtalk_dir /home/josh/projects/ece1195/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/ALU_Shift_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 24 20:57:12 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fbbd0d86-10bb-49ce-93bb-27c7fa638011" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "40f7eae7d8d34ef7804d1153ba012742" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "45" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7800X3D 8-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4541.264 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "32.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122576_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1609160814 -regid "" -xml /home/josh/projects/ece1195/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/ALU_Shift_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/josh/projects/ece1195/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/ALU_Shift_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/josh/projects/ece1195/lab_2/lab_2.sim/sim_1/behav/xsim/xsim.dir/ALU_Shift_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
